name: Build and Publish Docker Image
on:
  push:
    paths:
      - 'package.json'  # Trigger when `package.json` changes
    tags:
      - 'v*'  # Trigger on tags starting with "v"
  workflow_dispatch:  # Allow manual triggering
    inputs:
      version:
        description: "Specify a version (optional, overrides package.json file)"
        required: false
        default: ""
      
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4
        
      # Log in to Docker Hub or GitHub Container Registry
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      # Extract the version from the tag
      - id: get_version
        uses: battila7/get-version-action@v2
        
      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ vars.DOCKERHUB_IMAGE }}:latest .
          docker tag ${{ vars.DOCKERHUB_IMAGE }}:latest ${{ vars.DOCKERHUB_IMAGE }}:${{ steps.get_version.outputs.version }}
          
      # Push the Docker image
      - name: Push Docker Image
        run: |
          docker push ${{ vars.DOCKERHUB_IMAGE }}:latest
          docker push ${{ vars.DOCKERHUB_IMAGE }}:${{ steps.get_version.outputs.version }}
